import { formatDateTime } from '../utils/date.js';

export function renderWorkflowList({ workflows, search, onNew, onView, onEdit, onDelete }) {
  const container = document.querySelector('#workflow-list'); container.replaceChildren();
    const header = document.createElement('header'); header.className = 'list-header'; const top = document.createElement('div'); top.className = 'list-header__top'; const title = document.createElement('h1'); title.textContent = 'Workflows'; const button = document.createElement('button'); button.className = 'button button--primary'; button.type = 'button'; button.textContent = '+ New Workflow'; button.addEventListener('click', onNew); top.append(title, button); const input = document.createElement('input'); input.className = 'workflow-search'; input.type = 'search'; input.placeholder = 'Search workflows...'; input.value = search; input.addEventListener('input', () => renderWorkflowList({ workflows, search: input.value, onNew, onView, onEdit, onDelete })); header.append(top, input); container.append(header);
  const visible = workflows.filter((workflow) => { const haystack = `${workflow.name} ${workflow.promptNames || ''} ${workflow.categoryNames || ''}`.toLowerCase(); return haystack.includes(search.toLowerCase().trim()); });
    if (!visible.length) { const empty = document.createElement('div'); empty.className = 'empty-state'; empty.textContent = search ? 'No workflows match your search.' : 'Create your first workflow to connect prompts into a repeatable sequence.'; container.append(empty); return; } 
    const cards = document.createElement('div'); cards.className = 'workflow-cards'; container.append(cards);
    visible.forEach((workflow) => { const card = document.createElement('article'); card.className = 'workflow-card'; const info = document.createElement('div'); const title = document.createElement('h2'); title.textContent = workflow.name; const meta = document.createElement('p'); meta.textContent = `${workflow.stepCount} ${workflow.stepCount === 1 ? 'step' : 'steps'} · Updated ${formatDateTime(workflow.updatedAt)}`; info.append(title, meta); const actions = document.createElement('div'); actions.className = 'workflow-card__actions'; [['View', onView], ['Edit', onEdit]].forEach(([label, fn]) => { const button = document.createElement('button'); button.className = 'button button--secondary'; button.type = 'button'; button.textContent = label; button.addEventListener('click', () => fn(workflow.id)); actions.append(button); }); const del = document.createElement('button'); del.className = 'icon-button icon-button--danger'; del.type = 'button'; del.textContent = '⋯'; del.title = 'Delete workflow'; del.addEventListener('click', () => onDelete(workflow)); actions.append(del); card.append(info, actions); cards.append(card); });
}
