import { formatDateTime } from '../utils/date.js';

export function renderWorkflowList({ workflows, search, selectedWorkflowId, status = 'ready', onNew, onView, onEdit, onDelete }) {
  const container = document.querySelector('#workflow-list'); container.replaceChildren();
    const header = document.createElement('header'); header.className = 'list-header'; const top = document.createElement('div'); top.className = 'list-header__top'; const title = document.createElement('h1'); title.textContent = 'Workflows'; const button = document.createElement('button'); button.className = 'button button--primary'; button.type = 'button'; button.textContent = '+ New Workflow'; button.addEventListener('click', onNew); top.append(title, button); const input = document.createElement('input'); input.className = 'workflow-search'; input.type = 'search'; input.placeholder = 'Search workflows...'; input.value = search; input.addEventListener('input', () => renderWorkflowList({ workflows, search: input.value, selectedWorkflowId, status, onNew, onView, onEdit, onDelete })); header.append(top, input); container.append(header);
  const visible = workflows.filter((workflow) => { const haystack = `${workflow.name} ${workflow.promptNames || ''} ${workflow.categoryNames || ''}`.toLowerCase(); return haystack.includes(search.toLowerCase().trim()); });
    if (status === 'loading') { const loading = document.createElement('div'); loading.className = 'empty-state'; loading.textContent = 'Loading workflows...'; container.append(loading); return; }
    if (status === 'error') { const error = document.createElement('div'); error.className = 'empty-state'; error.textContent = 'Could not load workflows.'; container.append(error); return; }
    if (!visible.length) { const empty = document.createElement('div'); empty.className = 'empty-state'; empty.textContent = search ? 'No workflows match your search.' : 'No workflows yet'; container.append(empty); return; }
    const cards = document.createElement('div'); cards.className = 'workflow-cards'; container.append(cards);
    visible.forEach((workflow) => { const card = document.createElement('article'); card.className = `workflow-card${workflow.id === selectedWorkflowId ? ' workflow-card--selected' : ''}`; card.tabIndex = 0; card.setAttribute('aria-current', workflow.id === selectedWorkflowId ? 'true' : 'false'); card.addEventListener('click', () => onView(workflow.id)); card.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onView(workflow.id); } }); const info = document.createElement('div'); const title = document.createElement('h2'); title.textContent = workflow.name; const meta = document.createElement('p'); meta.textContent = `${workflow.stepCount} ${workflow.stepCount === 1 ? 'step' : 'steps'} · Updated ${formatDateTime(workflow.updatedAt)}`; info.append(title, meta); const actions = document.createElement('div'); actions.className = 'workflow-card__actions'; [['View', onView], ['Edit', onEdit]].forEach(([label, fn]) => { const button = document.createElement('button'); button.className = 'button button--secondary'; button.type = 'button'; button.textContent = label; button.addEventListener('click', (event) => { event.stopPropagation(); fn(workflow.id); }); actions.append(button); }); const del = document.createElement('button'); del.className = 'icon-button icon-button--danger'; del.type = 'button'; del.textContent = '⋯'; del.title = 'Delete workflow'; del.addEventListener('click', (event) => { event.stopPropagation(); onDelete(workflow); }); actions.append(del); card.append(info, actions); cards.append(card); });
}
